### ISSUE TITLE
please test if the event listener for calculating the height of the keyboard works

### ISSUE THREAD

**Issue by prasanta352** [applibgroup/KitKatEmoji#2]
**Describe the bug**
please test if the event listener for calculating the height of the keyboard works

**To Reproduce**
1. click on the input field 
2. check if the output field text change
3. dismiss the keyboard 
4. check if the output field text change
5. do same for open keyboard and close keyboard

**Expected behavior**
to change the output text when the keyboard open and close

**Screenshots**
![image](https://user-images.githubusercontent.com/32667365/144190673-87c0db17-c1c1-4fc4-8388-743e5b544ea2.png)

**Additional context**
I am trying to calculate the keyboard height for the device keyboard so I have added a listener to the main layout so when the keyboard opens the layout size get changes and we calculate the difference of the height. but the event is not firing in emulator so please check if it is working in real device.

the code is on https://github.com/prasanta352/KitKatEmoji/tree/keyboard-height-test

**Comment by kanaksony** [comment]
https://user-images.githubusercontent.com/6097596/144216867-7897a228-1fae-430a-9473-3459541465d3.mp4

**Comment by prasanta352** [comment]
I am trying to implement this [https://github.com/applibgroup/KitKatEmoji/blob/343420accf263d0b9b3d692e048a99bcada42264/kitkatemojiexample/src/main/java/com/sithagi/kitkatemojiexample/MainActivity.java#L193-L223](https://github.com/applibgroup/KitKatEmoji/blob/343420accf263d0b9b3d692e048a99bcada42264/kitkatemojiexample/src/main/java/com/sithagi/kitkatemojiexample/MainActivity.java#L193-L223) 

but the event listener is not firing 
[https://github.com/prasanta352/KitKatEmoji/blob/6a93e33330b9047329322b3dbc6b57971b666d57/entry/src/main/java/com/sithagi/kitkatemoji/MainAbility.java#L73-L90](https://github.com/prasanta352/KitKatEmoji/blob/6a93e33330b9047329322b3dbc6b57971b666d57/entry/src/main/java/com/sithagi/kitkatemoji/MainAbility.java#L73-L90)

**Comment by kanaksony** [comment]
You are using a deprecated function here. See the document for [onGlobalLayoutUpdated](https://developer.harmonyos.com/en/docs/documentation/doc-references/componenttreeobserver_globallayoutlistener-0000001054678677#ZH-CN_TOPIC_0000001054678677__onGlobalLayoutUpdated--).

Replace it with Component.LayoutRefreshedListener#onRefreshed(Component)

```private void checkKeyboardHeight(final Component parentLayout) {
        parentLayout.getComponentTreeObserver().setLayoutRefreshedListener(new ComponentTreeObserver.LayoutRefreshedListener() {
            @Override
            public void onRefreshed​(Component component) {
                new ToastDialog(getContext()).setText("onGlobalLayoutUpdated").setAlignment(LayoutAlignment.BOTTOM).show();
                Rect r = new Rect();
                parentLayout.getWindowVisibleRect(r);
                int screenHeight = parentLayout.getHeight();
                int heightDifference = screenHeight - (r.bottom);
                output.setText("" + r +
                        "\nscreenHeight= " + screenHeight +
                        "\nheightDifference: heightDifference" + heightDifference +
                        "\npreviousHeightDiffrence: " + previousHeightDiffrence
                );
                previousHeightDiffrence = heightDifference;
            }
        });
    }

**Comment by prasanta352** [comment]
**Test the app**
test if the app is now functional

**Steps**
1. click on the "smiling face" icon 
2. check if the emoji keyboard shows up
3. click on the "keyboard" icon
4. check if emoji keyboard hide and the device keyboard shows up
5. click on the "smiling face" icon and check if the emoji keyboard shows up and it is same height as the device keyboard
 

the code is on https://github.com/applibgroup/KitKatEmoji/pull/1
